# This docker compose start a Cherry runtime, based on Postgres, and attach a local folder
# In the local folder, Connector JAR file are present. Cherry runtime loads and start these connector

services:
  cherry-runtime:
    image: ghcr.io/camunda-community-hub/zeebe-cherry-runtime:latest
    container_name: cherryruntime
    ports:
      - "9081:9081"
    environment:
      - ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
      #      - ZEEBE_CLIENT_CLOUD_REGION=
      #      - ZEEBE_CLIENT_CLOUD_CLUSTERID=
      #      - ZEEBE_CLIENT_CLOUD_CLIENTID=
      #      - ZEEBE_CLIENT_CLOUD_CLIENTSECRET=
      - LOGGING_LEVEL_ROOT=INFO
      - spring.profiles.active=postgres
      - spring.datasource.url=jdbc:postgresql://postgres/cherrydb
      - spring.datasource.username=camunda
      - spring.datasource.password=camundapassword
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - org.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - cherry.connectorslib.uploadpath=/localstorage/uploadpath

  # save in the jarconnectors any connectors you want to upload at startup
    volumes:
      - ./jarconnectors:/localstorage/uploadpath
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - postgres

  postgres: # https://hub.docker.com/_/postgres
    container_name: postgres-cherry
    image: postgres:${POSTGRES_VERSION:-14.5-alpine}
    ports:
      - "5440:5432"

    environment:
      POSTGRES_DB: cherrydb
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camundapassword
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - camunda-platform

networks:
  camunda-platform:
